Support ubuntu 24.04 image
Package qemu no longer exists, but only qemu-user-static was required.
Also add support for RaspberryPi 5 emulation with a specific cpu_info to be
used on ubuntu-22.04 and cortex-a76 to be used on ubuntu-24.04.
Clarified that cpu_info is effectless with qemu 8.2+.
Also allow custom qemu.

Fix #90

Signed-off-by: Paul Guyot <pguyot@kallisys.net>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -96,8 +96,9 @@ runs:
   using: "composite"
   steps:
     - name: Install dependencies
-      run:
-        sudo apt-get update && sudo apt-get install -y qemu qemu-user-static binfmt-support parted wget dosfstools zip
+      run: |
+        sudo apt-get update && sudo apt-get install -y binfmt-support parted wget dosfstools zip
+        (test -x /usr/bin/qemu-arm-static && test -x /usr/bin/qemu-aarch64-static) || sudo apt install -y qemu-user-static
       shell: bash
     - name: Install qemu wrapper
       shell: bash
@@ -118,6 +119,9 @@ runs:
         cortex-a53)
             cpu="max:cortex-a53"
         ;;
+        cortex-a76)
+            cpu="max:cortex-a76"
+        ;;
         *)
             cpu=${{ inputs.cpu }}
         esac
@@ -125,8 +129,8 @@ runs:
         aarch64_cpu=${cpu#*:}
         sudo gcc -static ${GITHUB_ACTION_PATH}/qemu-wrapper.c -DQEMU_CPU=${arm_cpu} -O3 -s -o /usr/bin/qemu-arm-static0
         sudo gcc -static ${GITHUB_ACTION_PATH}/qemu-wrapper.c -DQEMU_CPU=${aarch64_cpu} -O3 -s -o /usr/bin/qemu-aarch64-static0
-        sudo update-binfmts --unimport qemu-arm
-        sudo update-binfmts --unimport qemu-aarch64
+        sudo update-binfmts --unimport qemu-arm || echo "warning: could not unimport qemu-arm"
+        sudo update-binfmts --unimport qemu-aarch64 || echo "warning: could not unimport qemu-aarch64"
         sudo update-binfmts --package arm-runner-action --install arm-runner-action-qemu-arm /usr/bin/qemu-arm-static0 --magic '\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00' --mask '\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff' --credentials yes --fix-binary yes
         sudo update-binfmts --package arm-runner-action --install arm-runner-action-qemu-aarch64 /usr/bin/qemu-aarch64-static0 --magic '\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00' --mask '\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff' --credentials yes --fix-binary yes
 
@@ -302,8 +306,8 @@ runs:
         sudo update-binfmts --package arm-runner-action --remove arm-runner-action-qemu-aarch64 /usr/bin/qemu-aarch64-static0
         sudo rm /usr/bin/qemu-arm-static0
         sudo rm /usr/bin/qemu-aarch64-static0
-        sudo update-binfmts --import qemu-arm
-        sudo update-binfmts --import qemu-aarch64
+        sudo update-binfmts --import qemu-arm || echo "warning: could not import qemu-arm"
+        sudo update-binfmts --import qemu-aarch64 || echo "warning: could not import qemu-aarch64"
 branding:
   icon: 'cpu'
   color: 'purple'
